### PR TITLE
Spanish translation added

### PR DESCRIPTION
**Pull request by lupa18**

### CODE REVIEW

**Comment by cryptogopher** [comment]
Thank you for your contribution @lupa18 ! There have been some additions/changes in 1.3 release recently. Do you want to update your translations before I merge them?

**Comment by lupa18** [comment]
I'm not sure, how can I get the changes? I must fork again the repo from 1.3 branch ?

**Comment by cryptogopher** [comment]
I think you can just compare current https://github.com/cryptogopher/issue_recurring/blob/master/config/locales/en.yml with your es.yml. Make changes in the branch you created pull request for and just commit. I think pull request will automatically include additional commits.

**Comment by lupa18** [comment]
ready !

**Pull request merged**
